title: <p align="center"> James Downs </p>

logo: "/images/profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jrdowns/">LinkedIn</a> |
  <a href="https://github.com/jrdowns">GitHub</a>
  </p>
  
  <p align="justify">
  "Perfection is the enemy of progress."
  <br><br>
  DevOps and Machine Learning Enthusiast.
  Certified TensorFlow Developer.
  Studying for GCP DevOps Engineer Certification.
  Currently completing my CS degree.
  <br><br>
  Systems Administrator at the University of North Texas.
  I am the primary Systems Administrator for the Central Web Service team.
  I manage the on-prem hosting for several hundred websites and 40+ servers.
  <br>
  My current technology stack:
  Linux (Ubuntu & RHEL)
  NGINX & Apache
  MariaDB/MySQL
  Ansible
  Jenkins
  Python
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
