title: <p align="center"> James Downs </p>

logo: "/images/profile.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume_two_columns.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jrdowns/">LinkedIn</a> |
  <a href="https://github.com/jrdowns">GitHub</a>
  </p>
  
  <p align="justify">
  DevOps and AI Enthusiast.
  <br><br>
  Certified TensorFlow Developer.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
